/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.digitalasset.ledger.client.{binding=>$u0020lfdomainapi}
package com.knoldus.model {
  object EventDecoder extends ` lfdomainapi`.EventDecoderApi(templateTypes = _root_.scala.collection.immutable.Seq[(` lfdomainapi`.TemplateCompanion[_$1] forSome { 
    type _$1
  })](com.knoldus.model.Main.Product, com.knoldus.model.Main.TransferOwnership, com.knoldus.model.Main.Proposal))
}
