/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.digitalasset.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.digitalasset.ledger.api.v1.{value=>$u0020rpcvalue}
package com.knoldus.model {
  package Main {
    final case class RejectOwnership() extends ` lfdomainapi`.ValueRef

    object RejectOwnership extends ` lfdomainapi`.ValueRefCompanion with _root_.scala.Function0[_root_.com.knoldus.model.Main.RejectOwnership] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`];
          new $anon()
        }
      };
      implicit val `RejectOwnership Value`: ` lfdomainapi`.Value[_root_.com.knoldus.model.Main.RejectOwnership] = {
        final class $anon extends this.`Value ValueRef`[_root_.com.knoldus.model.Main.RejectOwnership] {
          override def write(value: _root_.com.knoldus.model.Main.RejectOwnership): ` rpcvalue`.Value.Sum = ` record`();
          override def read(argValue: ` rpcvalue`.Value.Sum): _root_.scala.Option[_root_.com.knoldus.model.Main.RejectOwnership] = argValue.record.flatMap(((x$5) => _root_.scala.Some(RejectOwnership())))
        };
        new $anon()
      };
      override protected val ` dataTypeId` = ` mkDataTypeId`(`Package IDs`.Main, "Main", "RejectOwnership");
      implicit def `RejectOwnership LfEncodable`: ` lfdomainapi`.encoding.LfEncodable[_root_.com.knoldus.model.Main.RejectOwnership] = {
        final class $anon extends ` lfdomainapi`.encoding.LfEncodable[_root_.com.knoldus.model.Main.RejectOwnership] {
          override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): lte.Out[_root_.com.knoldus.model.Main.RejectOwnership] = {
            object `view ` extends view[lte.Field];
            lte.emptyRecord(` dataTypeId`, (() => _root_.com.knoldus.model.Main.RejectOwnership()))
          }
        };
        new $anon()
      }
    }
  }
}
